networks:
  web:
    external: true

services:
  evan:
    build: .
    restart: always
    ports:
      - "5555:3000"
    labels:
      - "traefik.http.routers.evan.tls=true"
      - "traefik.http.routers.evan.rule=Host(`evan.samsilver.ca`)"
    networks: web

