version: '3'
services:
  evan:
    build: .
    ports:
      - "5555:3000"
    labels:
      - "traefik.http.routers.evan.tls=true"
      - "traefik.http.routers.evan.rule=Host(`evan.samsilver.ca`)"
    network_mode: bridge
